<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Lindra_Market_v3</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>3.0.0</Version>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <InformationalVersion>v3.0.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="AppVersion" Value="$(InformationalVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.png" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <!-- lepoco/wpfui - latest stable as of Sep 2026 -->
    <PackageReference Include="WPF-UI" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketOffsets\MarketOffsets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Dvars\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Bo3\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
